# Generated by Django 3.2.12 on 2022-04-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='json',
            field=models.JSONField(null=True),
        ),
    ]
