# Generated by Django 3.2.12 on 2022-04-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0002_alter_pokemon_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('cost', models.PositiveIntegerField(null=True)),
                ('fling_power', models.PositiveIntegerField(null=True)),
                ('api_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('effect', models.TextField(null=True)),
                ('short_effect', models.CharField(max_length=500, null=True)),
                ('accuracy', models.PositiveIntegerField(null=True)),
                ('power', models.PositiveIntegerField(null=True)),
                ('pp', models.PositiveIntegerField(null=True)),
                ('priority', models.PositiveIntegerField(null=True)),
                ('api_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='avatar',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='held_items',
            field=models.ManyToManyField(to='monsters.HeldItem'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(to='monsters.Move'),
        ),
    ]
