# Generated by Django 3.2.12 on 2022-04-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_auto_20220411_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
