# Generated by Django 3.2.12 on 2022-04-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0005_auto_20220411_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helditem',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='move',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='helditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='helditem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
