# Generated by Django 3.2.12 on 2022-04-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0006_auto_20220411_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
